<?xml version='1.0'?>

<robot name="johnny" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.1415926535897931" />

    <xacro:property name="wheel_radius" value="0.216" />
    <xacro:property name="wheel_width" value="0.114" />
    <xacro:property name="wheel_mass" value="15" />
    <xacro:property name="wheel_to_track_ratio" value="0.5962" />

    <xacro:property name="axle_x_offset" value="0.395" />
    <xacro:property name="axle_y_offset" value="0.765" />

    <!-- base_link is on the ground plane, so the wheel axle is {wheel_radius} above it. -->
    <xacro:property name="axle_z_offset" value="${wheel_radius}" />

    <xacro:property name="diff_unit_length" value="1.34" />
    <xacro:property name="diff_unit_width" value="0.28" />
    <xacro:property name="diff_unit_height" value="0.63" />
    <xacro:property name="diff_unit_mass" value="50" />

    <xacro:property name="diff_unit_offset_x" value="0.00" />
    <xacro:property name="diff_unit_offset_y" value="0.56821" />
    <xacro:property name="diff_unit_offset_z" value="0.0" />

    <xacro:property name="chassis_length" value="1.35" />
    <xacro:property name="chassis_width" value="0.70" />
    <xacro:property name="chassis_height" value="0.30" />
    <xacro:property name="chassis_mass" value="100" />

    <xacro:property name="dummy_inertia" value="1e-09" />

    <!-- Include the xarm6 urdf -->
    <xacro:include filename="$(find xarm_description)/urdf/xarm_device_macro.xacro" />

    <!--
    Optional paint colors.
    Available colors:
      - yellow (default)
      - orange
      - olive
      - sand
  -->
    <xacro:property name="johnny_color" value="$(optenv johnny_COLOR yellow)" />
    <xacro:if value="${johnny_color == 'yellow'}">
        <xacro:property name="johnny_color_rgba" value="0.95 0.816 0.082 1.0" />
    </xacro:if>
    <xacro:if value="${johnny_color == 'orange'}">
        <xacro:property name="johnny_color_rgba" value="1.0 0.48 0.0 1.0" />
    </xacro:if>
    <xacro:if value="${johnny_color == 'olive'}">
        <xacro:property name="johnny_color_rgba" value="0.333 0.419 0.184 1.0" />
    </xacro:if>
    <xacro:if value="${johnny_color == 'sand'}">
        <xacro:property name="johnny_color_rgba" value="0.86 0.75 0.54 1.0" />
    </xacro:if>

    <xacro:macro name="wheel_inertia" params="m r h">
        <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
            iyy="${m*r*r/2}" iyz="0"
            izz="${m*(3*r*r+h*h)/12}" />
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
            iyy="${m*(x*x+z*z)/12}" iyz="0"
            izz="${m*(x*x+z*z)/12}" />
    </xacro:macro>

    <material name="dark_grey">
        <color rgba="0.2 0.2 0.2 1.0" />
    </material>
    <material name="light_grey">
        <color rgba="0.4 0.4 0.4 1.0" />
    </material>
    <material name="yellow">
        <color rgba="0.95 0.816 0.082 1.0" />
    </material>
    <material name="black">
        <color rgba="0.15 0.15 0.15 1.0" />
    </material>
    <material name="white">
        <color rgba="0.9 0.9 0.9 1.0" />
    </material>
    <material name="red">
        <color rgba="0.9 0.0 0.0 1.0" />
    </material>

    <xacro:macro name="wheel" params="prefix side *joint_pose">
        <link name="${prefix}_${side}_wheel_link">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheel_mass}" />
                <xacro:wheel_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" />
            </inertial>
            <!-- <visual>
                <origin xyz="0 0 0" rpy="0 0 ${PI/2}" />
                <geometry>
                    <mesh filename="package://johnny_description/meshes/wheel.stl" />
                </geometry>
                <material name="white" />
            </visual> -->
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}_${side}_wheel_joint" type="continuous">
            <parent link="base_link" />
            <child link="${prefix}_${side}_wheel_link" />
            <xacro:insert_block name="joint_pose" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <!-- Add wheels -->
    <xacro:wheel prefix="front" side="left">
        <origin xyz="${axle_x_offset*1} ${axle_y_offset*1} ${axle_z_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel prefix="front" side="right">
        <origin xyz="${axle_x_offset*1} ${axle_y_offset*-1} ${axle_z_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel prefix="rear" side="left">
        <origin xyz="${axle_x_offset*-1} ${axle_y_offset*1} ${axle_z_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel prefix="rear" side="right">
        <origin xyz="${axle_x_offset*-1} ${axle_y_offset*-1} ${axle_z_offset}" rpy="0 0 0" />
    </xacro:wheel>


    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://johnny_description/meshes/amiga_chassis_lowpoly.stl" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://johnny_description/meshes/amiga_chassis_lowpoly.stl" />

            </geometry>
        </collision>
    </link>


    <link name="gnss_link" />
    <joint name="gnss_link_joint" type="fixed">
        <origin xyz="0 0 1.76" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="gnss_link" />
    </joint>

    <link name="imu_link" />
    <joint name="imu_link_joint" type="fixed">
        <origin xyz="0 0 1.76" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="imu_link" />
    </joint>

    <link name="lidar_link" />
    <joint name="lidar_link_joint" type="fixed">
        <origin xyz="0.37 0 1.31" rpy="0 ${PI/6} 0" />
        <parent link="base_link" />
        <child link="lidar_link" />
    </joint>

    <link name="arm_link" />
    <joint name="arm_link_joint" type="fixed">
        <origin xyz="0.68 0 0.63" rpy="0 ${PI/2} 0" />
        <parent link="base_link" />
        <child link="arm_link" />
    </joint>

    <xacro:xarm_device dof="6" attach_to="arm_link" add_gripper="false" />

    <link name="multi_eef_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://johnny_description/meshes/multi_eef.obj" />
            </geometry>
            <material name="light_grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://johnny_description/meshes/multi_eef_collision.obj" />
            </geometry>
        </collision>
    </link>
    <joint name="multi_eef_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="link_eef" />
        <child link="multi_eef_link" />
    </joint>

    <link name="gripper_link">

    </link>
    <joint name="gripper_joint" type="fixed">
        <origin xyz="-0.139 0 0.125" rpy="0 ${-PI/3} 0" />
        <parent link="multi_eef_link" />
        <child link="gripper_link" />
    </joint>

</robot>
