controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    update_rate: 150
    xarm6_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    xarm_gripper_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController
xarm6_traj_controller:
  ros__parameters:
    action_monitor_rate: 10.0
    command_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.5
      joint1:
        goal: 0.01
        trajectory: 1.0
      joint2:
        goal: 0.01
        trajectory: 1.0
      joint3:
        goal: 0.01
        trajectory: 1.0
      joint4:
        goal: 0.01
        trajectory: 1.0
      joint5:
        goal: 0.01
        trajectory: 1.0
      joint6:
        goal: 0.01
        trajectory: 1.0
      stopped_velocity_tolerance: 0.0
    interface_name: position
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 25.0
xarm_gripper_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
    interface_name: position
    joints:
      - drive_joint
    state_interfaces:
      - position
      - velocity
